baseURL = 'https://example.org/'
languageCode = 'de-CH'
title = 'Valucor AG ORSA-Tool Dokumentation'
theme = 'hugo-book'
[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]']]
          inline = [['\(', '\)']]
[params]
  math = true