baseURL = "https://herbsi.github.io/orsa-tool-dokumentation"
languageCode = 'de-CH'
title = 'ORSA-Tool Dokumentation'
theme = 'hugo-book'
[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]']]
          inline = [['\(', '\)']]
[params]
  math = true
[caches]
  [caches.images]
    dir = ':cacheDir/images'
